# Generated by Django 5.2.2 on 2025-06-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('vinculacion', models.CharField(max_length=200)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aria.reunion')),
            ],
        ),
        migrations.AddField(
            model_name='reunion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aria.sede'),
        ),
    ]
