# Generated by Django 5.2.2 on 2025-06-08 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='vinculacion',
            field=models.CharField(choices=[('docente', 'Docente'), ('estudiante', 'Estudiante'), ('administrativo', 'Administrativo'), ('director', 'Director de Programa'), ('decano', 'Decano'), ('invitado', 'Invitado Externo'), ('graduado', 'Graduado')], max_length=200),
        ),
    ]
