# Generated by Django 5.2.2 on 2025-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0002_asistencia_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='es_graduado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='vinculacion',
            field=models.CharField(choices=[('docente', 'Docente'), ('estudiante', 'Estudiante'), ('administrativo', 'Administrativo'), ('director', 'Director de Programa'), ('decano', 'Decano'), ('invitado', 'Invitado Externo')], max_length=200),
        ),
    ]
