# Generated by Django 5.2.2 on 2025-06-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0003_remove_asistencia_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aria.sede'),
        ),
    ]
