# Generated by Django 5.2.2 on 2025-06-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0004_alter_reunion_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aria.reunion'),
        ),
    ]
