# Generated by Django 5.2.2 on 2025-06-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0005_alter_asistencia_reunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.reunion'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.sede'),
        ),
    ]
