# Generated by Django 5.2.2 on 2025-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0006_alter_asistencia_reunion_alter_reunion_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='vinculacion',
            field=models.CharField(blank=True, choices=[('docente', 'Docente'), ('estudiante', 'Estudiante'), ('administrativo', 'Administrativo'), ('director', 'Director de Programa'), ('decano', 'Decano'), ('invitado', 'Invitado Externo')], max_length=200),
        ),
    ]
